[package]
name = "app"
version = "0.1.0"
authors = ["Nathan Frasier <nanoshot.nf@gmail.com>"]
edition = "2018"

[dependencies]
pathfinding = "1"
rand = "0.5"
clap = { features = ["yaml"] }

[[bin]]
name = "app"
path = "src/rust/main.rs"